version: "3.9"

services:
  api01:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: api01
    environment:
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
    networks:
      - payment-processor
      - rinha-net
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "100MB"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    depends_on:
      - api01
    networks:
      - payment-processor
      - rinha-net

networks:
  payment-processor:
    external: true
  rinha-net:
    driver: bridge
