version: "3.9"

services:
  api01:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - ./tmp:/app/tmp # output binary
    hostname: api01
    ports:
      - "8080:8080"
    environment:
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
    networks:
      - payment-processor
      - rinha-net
    command: air

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    networks:
      - rinha-net

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    depends_on:
      - api01
    networks:
      - payment-processor
      - rinha-net

networks:
  payment-processor:
    external: true
  rinha-net:
    driver: bridge
